services:
  - type: web
    name: brilliox
    env: python
    python: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SERPER_KEYS
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
